#!/usr/bin/env bun
import { Command } from '@commander-js/extra-typings';
import initCommand from './src/commands/init/command';
import launchCommand from './src/commands/launch/command';

const program = new Command()
	.name('bank')
	.description('CLI for BANK token launch operations')
	.version('0.0.0')
	.addCommand(initCommand)
	.addCommand(launchCommand)
	.parse();

export default program;
