#!/usr/bin/env bun
import { Command } from '@commander-js/extra-typings';
import depositCommand from './src/commands/deposit/command';
import initCommand from './src/commands/init/command';
import launchCommand from './src/commands/launch/command';
import surfpoolCommand from './src/commands/surfpool/command';
import transitionCommand from './src/commands/transition/command';
import withdrawCommand from './src/commands/withdraw/command';

const program = new Command()
	.name('bank')
	.description('CLI for BANK token launch operations')
	.version('0.0.0')
	.addCommand(depositCommand)
	.addCommand(initCommand)
	.addCommand(launchCommand)
	.addCommand(transitionCommand)
	.addCommand(surfpoolCommand)
	.addCommand(withdrawCommand)
	.parse();

export default program;
